aviakassa/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()
admin.site.site_header = "АДМИНИСТРАТОРСКАЯ СИСТЕМА - АВИАКАССА"
admin.site.site_title = "UMSRA Admin Portal"
admin.site.index_title = "Добро пожаловать в систему администратора 'Авиакасса'!"

urlpatterns = [
    url(r"^", include("tickets.urls")),
    url('admin/', admin.site.urls, name='admin'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tickets/urls.py
from django.conf.urls import url, include
from django.urls import path
from .views import *
from aviakassa.urls import *

app_name = "tickets"

urlpatterns = [
    url(
        r'^$',
        CityListView.as_view(),
        name='home'
    ),
    url(
        r'^flights/$',
        SearchListView.as_view(),
        name='flights',
    ),
    url(
        r'^fl_error/$',
        ErrorView.as_view(),
        name='fl_error'
    ),
    # url(
    #     r'^flights/(?P<id>\d+)/$', 
    #     DetailFlightView.as_view(model=Flight), 
    #     name='flight_detail',
    # ),
    url(
        r'^about/',
        AboutUsView.as_view(),
        name='about',
    ),
]

# (?P<id>\d+)/

tickets/models.py
from django.db import models
import datetime
from django.utils import timezone
from .functions import *
# Create your models here.

TICKET_CLASS_CHOICES = (
    ('Первый класс', 'Первый класс'),
    ('Бизнес-класс', 'Бизнес-класс'),
    ('Эконом', 'Эконом')
)


class City(models.Model):
    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'

    name = models.CharField(
        max_length=100, verbose_name='Город', 
        null=True
    )
    en_name = models.CharField(
        max_length=100, verbose_name='Международное название города',
        null=True
    )

    def __str__(self):
        return self.name


class Airport(models.Model):
    class Meta:
        verbose_name = 'Аэропорт'
        verbose_name_plural = 'Аэропорты'

    iata_code = models.CharField(
        max_length=3,
        verbose_name='Код аэропорта',
        unique=True
    )
    air_name = models.CharField(
        max_length=100,
        verbose_name='Имя аэропорта'
    )
    city = models.ForeignKey(
        City, verbose_name='Город',
        on_delete=models.CASCADE,
    )

    class Meta:
        managed = False

    def __str__(self):
        return self.air_name


class PlaneType(models.Model):
    class Meta:
        verbose_name = 'Тип самолета'
        verbose_name_plural = 'Типы самолетов'

    name = models.CharField(
        max_length=35, verbose_name="Название типа самолета"
    )

    def __str__(self):
        return self.name


class Plane(models.Model):
    class Meta:
        verbose_name = 'Самолет'
        verbose_name_plural = 'Самолеты'

    name = models.CharField(
        max_length=35, verbose_name='Имя самолета', null=True,
    )
    pl_type = models.ForeignKey(
        PlaneType, verbose_name="Тип самолета",
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Flight(models.Model):
    class Meta:
        verbose_name = 'Рейс'
        verbose_name_plural = 'Рейсы'

    plane = models.ForeignKey(
      Plane, verbose_name='Самолет',
      on_delete=models.SET_NULL,
      null=True
    )
    takeoff_place = models.ForeignKey(
        Airport, verbose_name='Откуда',
        on_delete=models.SET_NULL,
        related_name="place_from",
        null=True
    )
    arrival_place = models.ForeignKey(
        Airport, verbose_name='Куда',
        on_delete=models.SET_NULL,
        related_name="place_to",
        null=True
    )
    takeoff_time = models.DateTimeField(
        null=True, verbose_name='Время отправления',
    )
    arrival_time = models.DateTimeField(
        null=True, verbose_name='Время прибытия',
    )
    seats_number = models.IntegerField(
        default=0, verbose_name='Количество билетов',
    )

    def __str__(self):
        return 'Маршрут: {} ({}) - {} ({}) || {} - {}'.format(
            self.takeoff_place.city.name, 
            self.takeoff_place.iata_code, 
            self.arrival_place.city.name,
            self.arrival_place.iata_code,
            self.takeoff_time.strftime('%d.%m.%Y %H:%M'),
            self.arrival_time.strftime('%d.%m.%Y %H:%M'),
        )
        

class Ticket(models.Model):
    class Meta:
        verbose_name = 'Билет'
        verbose_name_plural = 'Билеты'

    flight = models.ForeignKey(
        Flight, verbose_name="Номер рейса",
        on_delete=models.CASCADE,
    )
    is_bought = models.BooleanField(
        verbose_name='Куплен ли билет',
    )
    tickets_num = models.IntegerField(
        verbose_name='Количество билетов',
        default=0,
    )
    t_class = models.CharField(
        max_length=35, verbose_name='Класс билета',
        default=TICKET_CLASS_CHOICES[0][1], choices=TICKET_CLASS_CHOICES
    )
    price = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return '{}: {} || Рейс: ({} ({}) - {} ({}))'.format(
            self.t_class,
            how_price_is_it(self.price),
            self.flight.takeoff_place.city.name, 
            self.flight.takeoff_place.iata_code, 
            self.flight.arrival_place.city.name,
            self.flight.arrival_place.iata_code
        )


class Position(models.Model):
    class Meta:
        verbose_name = 'Должность'
        verbose_name_plural = 'Должности'

    name = models.CharField(
        max_length=55, null=True,
        verbose_name='Название должности'
    )

    def __str__(self):
        return self.name


class Employee(models.Model):
    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

    last_name = models.CharField(max_length=50, null=False, default='Петров', verbose_name="Фамилия")
    first_name = models.CharField(max_length=50, null=False, default='Григорий', verbose_name="Имя")
    patro = models.CharField(max_length=50, null=True, blank=True, verbose_name="Отчество")
    position = models.ForeignKey(Position, null=True, verbose_name="Должность", on_delete=models.SET_NULL)
    xp = models.IntegerField(default=0, null=False, verbose_name="Стаж")

    def __init__(self, *args, **kwargs):
        super(Employee, self).__init__(*args, **kwargs)
        if self.patro == None:
            self.patro = ' '

    def __str__(self):
        return '{} {} {} - {} (Стаж: {} {})'.format(self.last_name, self.first_name, self.patro, self.position, self.xp, xp_years(self.xp))


class AirlineTeam(models.Model):
    class Meta:
        verbose_name = 'Экипаж'
        verbose_name_plural = 'Экипажи'

    flight = models.ForeignKey(
        Flight, verbose_name="Назначенный вылет",
        on_delete=models.CASCADE,
    )
    worker = models.ForeignKey(
        Employee, verbose_name="Рабочий",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        if self.worker.patro == None:
            self.worker.patro = ' '
        return '{}: {} {} {} ({} ({}) - {} ({}))'.format(
            self.worker.position,
            self.worker.last_name,
            self.worker.first_name,
            self.worker.patro,
            self.flight.takeoff_place.city.name, 
            self.flight.takeoff_place.iata_code, 
            self.flight.arrival_place.city.name,
            self.flight.arrival_place.iata_code
        )

tickets/forms.py
import datetime as dt
from datetime import datetime
# from django_select2.forms import Select2Widget

from django import forms
from .models import *

def get_cities():
    cities = City.objects.all()
    return tuple((city.id, city.name) for city in cities)


class DateInput(forms.DateInput):
    input_type = 'date'


class CityManagerForm(forms.Form):
    class Meta:
        fields = {"takeoff_place", "arrival_place", "my_date"}

    takeoff_place = forms.ChoiceField(
        label="Откуда",
        choices=get_cities(),
        required=False,
        widget=forms.Select(choices=get_cities())
    )
    arrival_place = forms.ChoiceField(
        label="Куда",
        choices=get_cities(),
        required=False,
        widget=forms.Select(choices=get_cities())
    )
    my_date = forms.DateField(
        label="Дата",
        required=True,
        widget=DateInput(), 
    )

    def __init__(self, request, *args, **kwargs):
        super(CityManagerForm, self).__init__(request)
        self.fields['my_date'].error_messages = {'required': ' '}

    def clean_takeoff_place(self):
        takeoff_place = self.cleaned_data["takeoff_place"]
        if isinstance(takeoff_place, str):
            if not takeoff_place.strip():
                takeoff_place = None
        if takeoff_place:
            takeoff_place = City.objects.filter(id=takeoff_place)
        return takeoff_place

    def clean_arrival_place(self):
        arrival_place = self.cleaned_data["arrival_place"]
        if isinstance(arrival_place, str):
            if not arrival_place.strip():
                arrival_place = None
        if arrival_place:
            arrival_place = City.objects.filter(id=arrival_place)
        return arrival_place

    def clean(self):
        cleaned_data = super(CityManagerForm, self).clean()
        my_date = str(cleaned_data.get('my_date'))
        if my_date == None:
            my_date_time = datetime.datetime.strptime(my_date, '%Y-%m-%d').date()
            if datetime.datetime.now().date() <= my_date_time:
                msg = u"Wrong Date Time!"
                self.add_error('my_date', msg)
        return cleaned_data

tickets/views.py
from .models import *
from .forms import *
from .functions import *

from datetime import datetime, date
import datetime as dt

from rest_framework import serializers, status
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import AllowAny

from django.db.models import Q 
from django.views import generic
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, ListView


class CityListView(APIView):
    permission_classes = [AllowAny]
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'homePage.html'

    def get(self, request):
        example_form = CityManagerForm(request.GET)
        print(example_form)
        return Response({'takeoff': example_form})

    def post(self, request):
        form = CityManagerForm(request.POST)
        if form.is_valid():
            request.session['_old_post'] = request.POST
            if form.cleaned_data['my_date'] < datetime.now().date():
                request.session['error_message'] = '{} уже наступило. Попробуйте ввести другую дату.'.format(form.cleaned_data['my_date'].strftime('%d.%m.%Y'))
                return HttpResponseRedirect('fl_error/')
            elif form.cleaned_data['takeoff_place'] == None and form.cleaned_data['arrival_place'] == None:
                request.session['error_message'] = 'Не выбран авиамаршрут. Выберите авиамаршрут, пожалуйста.'
                return HttpResponseRedirect('fl_error/')
            elif list(tk.id for tk in form.cleaned_data['takeoff_place'])[0] is list(tk.id for tk in form.cleaned_data['arrival_place'])[0]:
                request.session['error_message'] = 'Совпадают точки вылета и прилета. Выберите две разные точки вылета и прилета.'
                return HttpResponseRedirect('fl_error/')
            else: 
                return HttpResponseRedirect('flights/')
        else:
            form = CityManagerForm(request.GET)
        return render(request, self.template_name, {'form': form})


class SearchListView(generic.ListView):
    model = Flight
    template_name = 'search_results.html'
    context_object_name = 'flight_list'

    def get_queryset(self): 
        t_list = list()
        a_list = list()
        first_form_data = self.request.session.pop('_old_post',{})
        if first_form_data:
            takeoffs = Airport.objects.filter(
                Q(city_id__in=first_form_data['takeoff_place'])
            )
            arrivals = Airport.objects.filter(
                Q(city_id__in=first_form_data['arrival_place'])
            )
            for t in takeoffs:
                t_list.append(t.id)
            for a in arrivals:
                a_list.append(a.id)
            my_date = first_form_data['my_date']
            date_time_obj = datetime.strptime(my_date, '%Y-%m-%d')
            flights = Flight.objects.filter(
                Q(takeoff_place_id__in=t_list) &
                Q(arrival_place_id__in=a_list) &
                Q(takeoff_time__date=datetime.date(date_time_obj))
            )
            print(flights)
            return flights.order_by('-takeoff_time').reverse()
        else:
            return Flight.objects.all().order_by('-takeoff_time').reverse()

    def get_context_data(self, **kwargs):
        flight_api_list = []
        context = super(SearchListView, self).get_context_data(**kwargs)
        context['airport_list'] = Airport.objects.all()
        context['city_list'] = City.objects.all()
        context['airline_team'] = AirlineTeam.objects.all()
        context['ticket_list'] = Ticket.objects.all()
        for fl in context['flight_list']:
            for airs in context['airport_list']:
                for cs in context['city_list']:
                    if (airs.id == fl.takeoff_place_id) and (cs.id == airs.city_id):
                        flight_api_list.append({
                            'id': fl.id,
                            'takeoff_id': fl.takeoff_place_id,
                            'name': airs.air_name,
                            'iata': airs.iata_code,
                            'city': cs.name,
                            'snum': fl.seats_number,
                            'tk_time': fl.takeoff_time,
                            'arr_time': fl.arrival_time,
                            'plane': fl.plane.name, 
                        })
                    for tk in flight_api_list:
                        if (tk['id'] == fl.id) and (airs.id == fl.arrival_place_id) and (cs.id == airs.city_id):
                            tk['arr_pl'] = fl.arrival_place_id
                            tk['arr_name'] = airs.air_name
                            tk['arr_iata'] = airs.iata_code
                            tk['arr_city'] = cs.name
                            tk['a_team'] = list(('{}: {} {} {} (Стаж: {} {})'.format(works.worker.position.name, works.worker.last_name, works.worker.first_name, works.worker.patro, works.worker.xp, xp_years(works.worker.xp))) for works in context['airline_team'] if (fl.id == works.flight_id))
                            tk['ticket'] = list(
                                ('{}: {}').format(ts.t_class, how_price_is_it(ts.price)) for ts in context['ticket_list'] if (fl.id == ts.flight_id)
                            )
        context['fapi_list'] = flight_api_list
        return context


class AboutUsView(TemplateView):
    template_name = 'thanks.html'

class ErrorView(APIView):
    permission_classes = [AllowAny]
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'fl_error.html'

    def get(self, request):
        error = request.session.pop('error_message',{})
        return Response({'error': error})

tickets/templates/fl_error.html
{% extends "wrapper.html" %}
{% load rest_framework %}
{% load static %}

{% block content %}
<div class="container has-text-centered">
    {% if error %}
        <img src="{% static 'images/error.png' %}">
        <h2>ОШИБКА!</h2>
        <p>{{ error }}</p>
    {% else %}
        <img src="{% static 'images/success.png' %}">
        <h2>Ошибки нет.</h2>
        <p>Попробуйте вернуться назад, пожалуйста.</p>
    {% endif %}
    <a class="btn btn-primary" href="{% url 'tickets:home' %}">Назад</a>
    <!-- <h1>Спасибо!</h1>
    <p>Сайт был создан на языке Python при помощи фреймворка Django<br> с использованием таких CSS- и JS-фреймворков для шаблонов, как:</p>
    <ul>
        <li>Ajax (JS)</li>
        <li>Bulma (CSS)</li>
        <li>Bootstrap 4 (CSS)</li>
        <li>JQuery (JS)</li>
    </ul>

    <p>©2021 Shadow Industries, Inc.</p> -->
</div>
{% endblock %}

tickets/templates/homePage.html
{% extends "wrapper.html" %}
{% load rest_framework %}

{% block content %}
<div class="container has-text-centered">
    <div class="column is-6 is-offset-3">
        <h1 class="title">
            АВИАКАССА
        </h1>
        <h2 class="subtitle">
            Поиск доступных рейсов
        </h2>
        <div class="field is-grouped">
            <form METHOD='POST' enctype="multipart/form-data">
                {% csrf_token %}
                {{ takeoff }}
                <input class="btn btn-primary" type="submit" value="OK">
            </form>
        </div>
    </div>
</div>
{% endblock %}

tickets/templates/search_results.html
{% extends "wrapper.html" %}
{% load rest_framework %}

{% block content %}
<div class="container has-text-centered">
    {% if flight_list %}
    <h1>Доступные рейсы на данный момент:</h1>
    <ul>

      {% for tk in fapi_list %}
      <li>
        <article class="message is-info" style="margin-top: 30px; margin-bottom: 30px;">
          <div class="message-header">
            <p>{{ tk.city }} ({{ tk.iata }}) - {{ tk.arr_city }} ({{ tk.arr_iata }})</p>
          </div>
          <div class="message-body">
            <div class="container">
              <div class="columns">
                <div class="column"><p>Время вылета:</p><p>{{ tk.tk_time }}</p></div>
                <div class="column"><p>Время прилета:</p><p>{{ tk.arr_time }}</div>
                <div class="column"><p>Количество свободных мест:</p><p>{{ tk.snum }}</div>
                <div class="column"><p>Самолет:</p><p>{{ tk.plane }}</div>
              </div>
              <hr></hr>
              <div class="columns">
                <div class="column">
                <div class="container">
                {% if tk.a_team %}
                <p align="left" class="is-info">Работают:</p></p>
                {% for emps in tk.a_team %}
                  <p align="left" class="is-info">{{ emps }}</p>
                {% endfor %}
                {% else %}
                  <p align="left" class="is-info">На данный рейс не назначен экипаж.</p>
                {% endif %}
                </div>
                </div>
                <div class="column">
                  <div class="container">
                  {% if tk.ticket %}
                  <p class="is-info" align="right">Доступные билеты в продаже:</p></p>
                  {% for ts in tk.ticket %}
                    <p class="is-info" align="right">{{ ts }}</p>
                  {% endfor %}
                  {% else %}
                    <p class="is-info" align="right">Билеты недоступны.</p>
                  {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </article>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p class="is-info">Доступных рейсов на данный момент нет :(</p>
      <a class="btn btn-primary" href="{% url 'tickets:home' %}">Назад</a>
    {% endif %} 
</div>
{% endblock %}

tickets/templates/thanks.html
{% extends "wrapper.html" %}
{% load rest_framework %}

{% block content %}
<div class="container has-text-centered">
    <h1>Спасибо!</h1>
    <p>Сайт был создан на языке Python при помощи фреймворка Django<br> с использованием таких CSS- и JS-фреймворков для шаблонов, как:</p>
    <ul>
        <li>Ajax (JS)</li>
        <li>Bulma (CSS)</li>
        <li>Bootstrap 4 (CSS)</li>
        <li>JQuery (JS)</li>
    </ul>

    <p>©2021 Shadow Industries, Inc.</p>
</div>
{% endblock %}

tickets/templates/wrapper.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">

        <script src="https://kit.fontawesome.com/c38f038e05.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <!-- jQuery -->
        <!-- <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" /> -->

        <!-- jQuery -->
        <!-- <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script> -->

        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"> 
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>

        {% load static %}
        {% load rest_framework %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Авиакасса - определяем лучшие билеты!</title>
        <style>
            ul{ 
                display: inline-block;
                *display: inline; /* IE7 */
                *zoom:1;  /* IE7 */ 
                list-style: none;
                width: 100%
            }
        </style>
    </head>
    <body>
        <section class="hero is-info is-fullheight">
            

            <div class="hero-head">
                <nav class="navbar navbar-expand-lg navbar-light mb-3" style="background-color: rgb(20, 9, 116);">
                    <a class="navbar-brand"><img src="{% static 'images/aviakassa.png' %}" width='40' height='40'></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                        <span style="color: #1f4ad6" class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarText">
                        <ul class="navbar-nav mr-auto mt-2 mt-lg-0" id="w" style="align-items: center;">
                            <li class="nav-item">
                                <a style="color: #ffffff" class="nav-link" href="{% url 'tickets:home' %}">ГЛАВНАЯ СТРАНИЦА</a>
                            </li>
                            <li class="nav-item">
                                <a style="color: #ffffff" class="nav-link" href="{% url 'admin:index' %}">АДМИНИСТРАТОР</a>
                            </li>
                            <li class="nav-item">
                                <a style="color: #ffffff" class="nav-link" href="{% url 'tickets:about' %}">О НАС</a>
                            </li>
                        </ul>
                    </div>
                </nav>
                <!-- <nav class="navbar is-fixed-top is-transparent" role="navigation" aria-label="main navigation">

                    <div class="container">
                  
                      <div class="navbar-brand">
                        
                        
                        
                        <a class="navbar-item">
                          <img class="homepage-img navbar-item" src="{% static 'images/aviakassa.png' %}" alt="Social Media for Smarter Marketing">
                        </a>
                        
                       
                        <a role="button" class="navbar-burger burger has-text-black" aria-label="menu" aria-expanded="false" data-target="navbar-menu">
                          <span aria-hidden="true"></span>
                          <span aria-hidden="true"></span>
                          <span aria-hidden="true"></span>
                        </a>
                      </div>
                  
                      <div id="navbar-menu" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{% url 'tickets:home' %}" class="navbar-item is-uppercase">
                                Домашняя страница
                            </a>
                        </div>
                          <a href="{% url 'admin:index' %}" class="navbar-item is-uppercase">
                            Режим администратора
                          </a>
                          <a href="/about/" class="navbar-item is-uppercase">
                            О нас
                          </a>
                        </div>
                      </div>
                  </nav> -->
            </div>
            <div class="hero-body">
                {% block content %}

                {% endblock %}
            </div>
        </section>
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/bulma-collapsible.min.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>